import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { graduate, memoryWorklist, park } from '/repo/packages/librarian/src/graduation/graduation.ts';

const base = '/work/memory-challenge';
const folder = `${base}/checkout/memory`;
mkdirSync(folder, { recursive: true });
mkdirSync(`${base}/outside`, { recursive: true });
const target = `${base}/outside/synthetic.txt`;
const link = `${folder}/linked.md`;
const ordinary = `${folder}/ordinary.md`;
writeFileSync(target, 'SYNTHETIC_OUTSIDE_TEXT');
writeFileSync(ordinary, 'Ordinary memory.');
writeFileSync(`${folder}/MEMORY.md`, '- [Ordinary](ordinary.md)\n');
symlinkSync('../../outside/synthetic.txt', link);
const items = await memoryWorklist([folder]);
assert.equal(items.find(x => x.file === link)?.text, 'SYNTHETIC_OUTSIDE_TEXT');
assert.equal(items.find(x => x.file === ordinary)?.text, 'Ordinary memory.');
assert.equal(items.some(x => x.file.endsWith('/MEMORY.md')), false);
await park(ordinary, 'A synthetic reviewed memory.');
assert.equal((await memoryWorklist([folder])).some(x => x.file === ordinary), false);
const fields = { title: 'Synthetic lesson' };
const refused = { async writeKnowledge() { throw new Error('synthetic refusal'); } };
await assert.rejects(graduate(refused as never, ordinary, 'principle', fields), /synthetic refusal/);
assert.equal(existsSync(ordinary), true);
const accepted = { async writeKnowledge(kind: string, written: object) { return { id: 'synthetic-note', type: kind, fields: written }; } };
await graduate(accepted as never, ordinary, 'principle', fields);
assert.equal(existsSync(ordinary), false);
assert.equal(readFileSync(`${folder}/MEMORY.md`, 'utf8'), '');
await graduate(accepted as never, link, 'principle', fields);
assert.equal(existsSync(link), false);
assert.equal(readFileSync(target, 'utf8'), 'SYNTHETIC_OUTSIDE_TEXT');
await graduate(accepted as never, target, 'principle', fields);
assert.equal(existsSync(target), false);
console.log(JSON.stringify({ passed: true, symlinkReadOutside: true, normalMemoryRead: true, parkHidesUnchangedMemory: true, refusedWritePreservesFile: true, ordinaryGraduationDeletesMemory: true, symlinkGraduationPreservesTarget: true, explicitNonMemoryPathDeleted: true, limitation: 'Accepted/refused library responses are inert stubs; no host caller authorization or real library write was tested.' }));
