// bake-kit.ts — write the baked kit to disk.
//
// ADR-0217 D4: parts bake at BUILD TIME and the runtime composes them. This is the build
// step. `baked/kit.json` is a generated artifact that is nonetheless committed, for the
// same reason the corpus seed is: the surface that consumes it (the studio) must be able
// to import it without a build step running first, and a reviewer must be able to see the
// diff when a building's geometry changes.
//
// It cannot silently go stale — `kit.test.ts` re-bakes and compares, so an edit to a
// building factory that is not followed by `pnpm bake:kit` fails the gate.
//
//   pnpm --filter @storytree/procedural-architecture bake

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bakeKit } from '../src/kit.js';
import { bakeHeroKit } from '../src/hero-kit.js';
import { bakeStone } from '../src/landscape/standing-stone.js';

const here = dirname(fileURLToPath(import.meta.url));
const bakedDir = resolve(here, '..', 'baked');
mkdirSync(bakedDir, { recursive: true });

const GENERATED = (guard: string): string =>
  `GENERATED by \`pnpm --filter @storytree/procedural-architecture bake\` — do not hand-edit. ${guard} fails if this drifts from a fresh bake.`;

// --- buildings (ADR-0217) ---------------------------------------------------
// `polys` is the world-space debugging receipt — useful to a test holding the ORDER to
// account, useless to a surface painting the result, and by far the largest thing in the
// bake. Dropping it is the difference between a ~1 MB asset and a ~10 MB one.
const kit = bakeKit();
// --- the cosy-island heroes (grounded-art inc 10) --------------------------
// A SECOND named roster in the same file: the fixed garden pieces (cottage / gazebo /
// autumn tree / stepping stone) the concept island is composed from (increment 11). They
// ride alongside `entries` so the existing building bake stays byte-for-byte unchanged and
// the studio's `loadFactoryKit` (which reads `.entries`) is untouched.
const heroes = bakeHeroKit();
const kitOut = resolve(bakedDir, 'kit.json');
writeFileSync(
  kitOut,
  JSON.stringify(
    {
      note: GENERATED('kit.test.ts'),
      entries: kit.map(({ polys: _polys, ...rest }) => rest),
      heroes: heroes.map(({ polys: _polys, ...rest }) => rest),
    },
    null,
    2,
  ) + '\n',
  'utf8',
);
const kitNodes = kit.reduce((n, e) => n + e.nodes.length, 0);
const heroNodes = heroes.reduce((n, e) => n + e.nodes.length, 0);
console.log(`baked ${kit.length} buildings, ${kitNodes} nodes → ${kitOut}`);
console.log(`baked ${heroes.length} heroes, ${heroNodes} nodes → ${kitOut}`);

// --- the standing stone (ADR-0218, the first landscape type) ----------------
// A SEPARATE asset, not a kit entry: a stone is its own object type (ADR-0217 D1), and the
// scene composes it into the shared scene-graph rather than as studio chrome.
const stone = bakeStone();
const stoneOut = resolve(bakedDir, 'stone.json');
writeFileSync(
  stoneOut,
  JSON.stringify({ note: GENERATED('standing-stone.test.ts'), stone }, null, 2) + '\n',
  'utf8',
);
console.log(`baked the standing stone, ${stone.nodes.length} nodes → ${stoneOut}`);
