// bake-kit.ts — write the baked kit to disk.
//
// ADR-0217 D4: parts bake at BUILD TIME and the runtime composes them. This is the build
// step. `baked/kit.json` is a generated artifact that is nonetheless committed, for the
// same reason the corpus seed is: the surface that consumes it (the studio) must be able
// to import it without a build step running first, and a reviewer must be able to see the
// diff when a building's geometry changes.
//
// It cannot silently go stale — `kit.test.ts` re-bakes and compares, so an edit to a
// building factory that is not followed by `pnpm bake:kit` fails the gate.
//
//   pnpm --filter @storytree/procedural-architecture bake

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { bakeKit } from '../src/kit.js';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '..', 'baked', 'kit.json');

const kit = bakeKit();
mkdirSync(dirname(out), { recursive: true });

// `polys` is the world-space debugging receipt — useful to a test holding the ORDER to
// account, useless to a surface painting the result, and by far the largest thing in the
// bake. Dropping it is the difference between a ~1 MB asset and a ~10 MB one.
const asset = {
  note: 'GENERATED by `pnpm --filter @storytree/procedural-architecture bake` — do not hand-edit. kit.test.ts fails if this drifts from a fresh bake.',
  entries: kit.map(({ polys: _polys, ...rest }) => rest),
};

writeFileSync(out, JSON.stringify(asset, null, 2) + '\n', 'utf8');

const nodes = kit.reduce((n, e) => n + e.nodes.length, 0);
console.log(`baked ${kit.length} buildings, ${nodes} nodes → ${out}`);
