<#
.SYNOPSIS
  Withdraw the managed Codex containment boundary (ADR-0390 D2). Operator-run, elevated.

.DESCRIPTION
  ADR-0390 retires the containment posture ADR-0355/0364/0368/0375/0379 built, and puts an
  interactive Codex session at Claude parity. That has TWO halves and the second is easy to forget:

    1. the managed configuration - C:\ProgramData\OpenAI\Codex\requirements.toml, which carries
       default_permissions, allow_managed_hooks_only, the three storytree_codex_* profiles, and the
       SessionStart / PreToolUse / PermissionRequest hook wiring; and
    2. the deny ACEs that boundary applied to the filesystem, which are ON DISK and SURVIVE the
       config's removal.

  Removing only (1) leaves `.git` unwritable for the sandbox account, so Codex still cannot run
  `git worktree add` - the exact failure ADR-0390 exists to clear. This script does both.

  DRY RUN BY DEFAULT. It prints every change it would make and touches nothing. Pass -Apply to act.

.PARAMETER Apply
  Actually make the changes. Without it the script only reports.

.PARAMETER Repo
  The primary checkout (the "lobby"). Defaults to C:\code\storytree.

.NOTES
  SAFETY. This only ever removes access-control entries that are ALL of: DENY, NOT inherited, and
  owned by a Codex sandbox principal (the sandbox capability SID, or a CodexSandbox* account). It
  never touches an Allow rule, never touches an inherited rule, and never touches any other
  identity. Anything it cannot classify is reported and skipped.

  REVERSIBLE. The managed config is RENAMED, not deleted, so re-enabling is a rename back. The ACEs
  are not backed up individually - they are regenerated by re-running the boundary installer, which
  is the supported way to restore the fence. `C:\ProgramData\OpenAI\Codex\Storytree` (the hook and
  the pinned bootstrap payload) is deliberately LEFT IN PLACE: it is inert once the config is gone.

  ADR-0390 D7: an agent may neither run this nor ask an operator to run it. It is an operator action.
#>
[CmdletBinding()]
param(
  [switch]$Apply,
  [string]$Repo = 'C:\code\storytree'
)

$ErrorActionPreference = 'Stop'

function Test-Elevated {
  $id = [Security.Principal.WindowsIdentity]::GetCurrent()
  (New-Object Security.Principal.WindowsPrincipal($id)).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
}

# A Codex sandbox principal: the unresolvable capability SID the elevated sandbox mints, or a named
# CodexSandbox* account. Deliberately narrow - an identity that matches neither is left alone.
function Test-SandboxPrincipal([string]$identity) {
  if ($identity -match 'CodexSandbox') { return $true }
  # An unresolvable S-1-5-21-* SID under this machine's domain, as the sandbox capability appears.
  if ($identity -match '^S-1-5-21-\d+-\d+-\d+-\d+$') {
    try {
      [void](New-Object Security.Principal.SecurityIdentifier($identity)).Translate(
        [Security.Principal.NTAccount])
      return $false   # it resolves to a real account - not the sandbox capability; leave it
    } catch { return $true }
  }
  return $false
}

if ($Apply -and -not (Test-Elevated)) {
  throw 'Run this from an ELEVATED PowerShell. ProgramData and these ACLs both require it.'
}

$mode = if ($Apply) { 'APPLY' } else { 'DRY RUN (pass -Apply to act)' }
Write-Host "Codex boundary withdrawal (ADR-0390) - $mode`n" -ForegroundColor Cyan

# ---------------------------------------------------------------- 1. the managed configuration
$managed = 'C:\ProgramData\OpenAI\Codex\requirements.toml'
Write-Host '[1] managed configuration' -ForegroundColor Cyan
if (Test-Path $managed) {
  $stamp = (Get-Item $managed).LastWriteTime.ToString('yyyyMMdd-HHmmss')
  $target = "$managed.disabled-$stamp"
  Write-Host "    rename  $managed"
  Write-Host "        ->  $target"
  if ($Apply) {
    Move-Item -LiteralPath $managed -Destination $target
    Write-Host '    done.' -ForegroundColor Green
  }
} else {
  Write-Host '    already absent - nothing to disable.' -ForegroundColor Green
}

# ---------------------------------------------------------------- 2. the deny ACEs it applied
# Every path the boundary is known to fence. The worktree entries are enumerated rather than
# assumed: the generated profile listed one block PER SLOT, so the ACEs are per slot too.
$targets = [System.Collections.Generic.List[string]]::new()
$targets.Add((Join-Path $Repo '.git'))
# `.codex` BEFORE `.codex\auth.json` on purpose: the directory carries explicit deny rules of its
# own, and auth.json INHERITS one of them. Removing only the file's explicit rules leaves the
# inherited deny in force, which reads as "cleared" while still blocking - measured 2026-08-20,
# auth.json had 3 deny rules of which 1 was inherited from the parent.
foreach ($p in @(
    "$env:USERPROFILE\.storytree",
    "$env:USERPROFILE\.codex",
    "$env:USERPROFILE\.codex\auth.json",
    "$env:APPDATA\gcloud",
    "$env:USERPROFILE\.config\gcloud")) { $targets.Add($p) }

$worktrees = Join-Path $Repo '.claude\worktrees'
if (Test-Path $worktrees) {
  foreach ($d in Get-ChildItem $worktrees -Directory -ErrorAction SilentlyContinue) {
    foreach ($leaf in @('.git', '.codex')) {
      $c = Join-Path $d.FullName $leaf
      if (Test-Path $c) { $targets.Add($c) }
    }
  }
}

Write-Host "`n[2] deny ACEs on $($targets.Count) path(s)" -ForegroundColor Cyan
$removed = 0; $touched = 0; $skipped = @()

foreach ($path in $targets) {
  if (-not (Test-Path -LiteralPath $path)) { continue }
  $acl = Get-Acl -LiteralPath $path
  $doomed = @($acl.Access | Where-Object {
    $_.AccessControlType -eq 'Deny' -and -not $_.IsInherited -and
    (Test-SandboxPrincipal $_.IdentityReference.Value)
  })
  $foreign = @($acl.Access | Where-Object {
    $_.AccessControlType -eq 'Deny' -and -not $_.IsInherited -and
    -not (Test-SandboxPrincipal $_.IdentityReference.Value)
  })
  if ($foreign.Count -gt 0) {
    $skipped += "$path ($($foreign.Count) non-sandbox deny rule(s) left untouched)"
  }
  if ($doomed.Count -eq 0) { continue }

  $touched++; $removed += $doomed.Count
  Write-Host ("    {0,-4} {1}" -f "-$($doomed.Count)", $path)
  if ($Apply) {
    foreach ($rule in $doomed) { [void]$acl.RemoveAccessRuleSpecific($rule) }
    Set-Acl -LiteralPath $path -AclObject $acl
  }
}

Write-Host ("`n    {0} deny rule(s) across {1} path(s)." -f
  $(if ($Apply) { "removed $removed" } else { "would remove $removed" }), $touched)
if ($skipped.Count -gt 0) {
  Write-Host "`n    left alone (not a Codex sandbox principal):" -ForegroundColor Yellow
  $skipped | ForEach-Object { Write-Host "      $_" -ForegroundColor Yellow }
}

# ---------------------------------------------------------------- 3. verify nothing is left behind
# A half-removed boundary is the failure this script exists to prevent, and it is INVISIBLE from the
# removal count alone: an inherited deny survives its child's cleanup, and a path nobody enumerated
# is never reported at all. So re-read every target and say plainly whether any sandbox deny remains,
# inherited ones included. In dry-run this describes the CURRENT state, which is the useful baseline.
Write-Host "`n[3] verification" -ForegroundColor Cyan
$leftover = @()
foreach ($path in $targets) {
  if (-not (Test-Path -LiteralPath $path)) { continue }
  $rest = @((Get-Acl -LiteralPath $path).Access | Where-Object {
    $_.AccessControlType -eq 'Deny' -and (Test-SandboxPrincipal $_.IdentityReference.Value)
  })
  if ($rest.Count -gt 0) {
    $inh = @($rest | Where-Object { $_.IsInherited }).Count
    $leftover += ("{0}  ({1} deny rule(s){2})" -f $path, $rest.Count,
      $(if ($inh -gt 0) { ", $inh INHERITED - fix the parent" } else { "" }))
  }
}
if ($leftover.Count -eq 0) {
  Write-Host '    no sandbox deny rules remain on any known path.' -ForegroundColor Green
} elseif ($Apply) {
  Write-Host '    STILL FENCED - these paths kept a sandbox deny:' -ForegroundColor Red
  $leftover | ForEach-Object { Write-Host "      $_" -ForegroundColor Red }
  Write-Host '    An inherited rule cannot be removed at the child; clear it on the parent.'
} else {
  Write-Host "    $($leftover.Count) path(s) currently fenced (this is the before picture):"
  $leftover | Select-Object -First 8 | ForEach-Object { Write-Host "      $_" }
  if ($leftover.Count -gt 8) { Write-Host "      ... and $($leftover.Count - 8) more" }
}

# ---------------------------------------------------------------- 4. what the operator does next
Write-Host "`n[4] next" -ForegroundColor Cyan
if (-not $Apply) {
  Write-Host '    Re-run with -Apply from an elevated shell to make these changes.'
} else {
  Write-Host '    RESTART the Codex desktop app - the managed config is read at startup.'
  Write-Host '    Then verify parity from a Codex task, in this order:'
  Write-Host '      1. write a file in the lobby        (should now SUCCEED)'
  Write-Host '      2. git worktree add ...             (should now SUCCEED - this was the blocker)'
  Write-Host '      3. storytree library artifact <id> --pg   (should now READ - credentials + network)'
  Write-Host '    If 2 still fails on .git permissions, this script missed a path: re-run it.'
}
Write-Host ''
