// plant-geometry.ts — PROCEDURAL PLANT MESHES for the live-render experiment. Pure,
// deterministic, browser-free, node:test-provable: it emits plain typed arrays and imports
// no three.js, so it sits inside the ADR-0123 provability firewall with the rest of the
// experiment's thinking half.
//
// THIS IS THE ARC'S OWN PREMISE, ONE SUBSTRATE OVER. Chapter 2's code-generated-art arc is
// art made by OUR OWN CODE rather than by an image model, and every plant it has shipped so
// far was hand-modelled in Blender, rendered to a raster, and snapped to a closed palette.
// The renderer changes; the premise does not. A live plant is still generated by code from
// a seed, still deterministic, still banded to the authored palette.
//
// WHY GEOMETRY IS THE RIGHT LEVER HERE AND WAS THE WRONG ONE BEFORE. The arc measured
// geometry out for the SPRITE path, and correctly: at ONE GROUND UNIT = ONE DELIVERED PIXEL
// a shrub is ~12 px, and the 3x3 majority downsample WELDS fine structure into a mass
// (hair at tutorial scale delivered zero pixels; thick hair delivered a near-solid 9x8
// rectangle). Detail finer than the quantiser is discarded before delivery, so no amount of
// modelling survived. A live renderer removes the quantiser, not the modelling — which is
// why the same lever that was measured out is now the one worth pulling.
//
// THE SIZE CONTRACT IS MECHANICAL, NOT PROMISED. `fitToFootprint` scales every generated
// mesh so its bounding box IS the footprint the SVG surface's own marks occupy, and a test
// asserts it. This arc nearly published "hair delivers more pixels than the hand-modelled
// dome" when the truth was that hair was a bigger object — arithmetic wearing a technique's
// costume. Making the match a property of the generator, rather than of the person setting
// up the comparison, is what stops that recurring.

import {
  addLobe,
  basisFromUp,
  emptyRaw,
  fitToFootprint,
  mulberry32,
  type GeneratedMesh,
  type Raw,
} from './mesh-kit.js';

/** A generated mesh — the shared shape, named here for the callers that already speak it.
 *  The primitives that build one live in `mesh-kit.ts`, which the UAT-flower and story-tree
 *  generators build out of too. */
export type PlantMesh = GeneratedMesh;

/** The knobs a caller may turn. Everything else is derived, so two callers asking for the
 *  same plant get the same plant. */
export interface PlantSpec {
  /** Deterministic seed — the same seed always yields the same plant. */
  seed: number;
  /** Which form family to grow (from the plant descriptor). */
  form: 'blade' | 'shrub' | 'stem' | 'flower' | 'mixed';
  /** Target footprint in world units: the box the SVG surface's marks occupy. */
  width: number;
  /** Target footprint height in world units. */
  height: number;
  /** Geodesic subdivision per lobe, 0..3. The DETAIL LADDER: this is the knob the
   *  experiment sweeps, because it is the thing a live renderer can spend that the sprite
   *  path provably could not. */
  detail?: number;
  /** The SILHOUETTE style.
   *
   *  `mound` (the default, and the original) stacks axis-aligned ellipsoid lobes. The owner
   *  looked at it on 2026-08-19 and called it "circular swirls", which is a fair reading of
   *  what it is: every lobe is a sphere scaled on the world axes, so the outline is a union
   *  of circles and the banded shading lays concentric rings inside each one — the rings
   *  ARE the swirl.
   *
   *  `foliage` keeps everything else identical — same lobe count, same placement draws, same
   *  ladder, same footprint fit — and changes only each lobe's ORIENTATION and PROPORTION:
   *  lobes are flattened into leaf-like discs and tilted onto their own axes, so neither the
   *  outline nor the shading rings stay circular. It is a silhouette answer, which is the
   *  lever the arc measured as the affordable one (0 palette entries). */
  style?: 'mound' | 'foliage';
}

/**
 * Grow one plant. Deterministic in `spec.seed`, fitted to `spec.width` x `spec.height`.
 *
 * The forms are deliberately COARSE and carry no meaning. ADR-0226 D2 gives the vegetation
 * signal to the COUNT of plants; a species that meant something would invent a semantic
 * channel under cover of an art change, which is the ADR-0367 D5 failure (art asserting a
 * state the work does not hold).
 */
export function growPlant(spec: PlantSpec): PlantMesh {
  const detail = Math.max(0, Math.min(3, spec.detail ?? 2));
  const style = spec.style ?? 'mound';
  const rand = mulberry32(spec.seed);
  const raw: Raw = emptyRaw();

  const lobeCount =
    spec.form === 'blade' ? 5 : spec.form === 'stem' ? 3 : spec.form === 'flower' ? 4 : 6;

  for (let i = 0; i < lobeCount; i++) {
    // A mound: lobes crowd the base and thin toward the crown, so the silhouette reads as
    // a plant rather than as a ball. Every draw comes from `rand` in a fixed order.
    const t = i / Math.max(1, lobeCount - 1);
    const ang = rand() * Math.PI * 2;
    const spread = (1 - t) * 0.55 + 0.08;
    const r = Math.sqrt(rand()) * spread;
    const cx = Math.cos(ang) * r;
    const cz = Math.sin(ang) * r;
    const cy = t * 0.62 + rand() * 0.12;
    const lobeR = (0.42 - t * 0.2) * (0.75 + rand() * 0.5);
    const squash = spec.form === 'blade' ? 1.55 : spec.form === 'stem' ? 1.9 : 0.82;

    if (style === 'mound') {
      addLobe(raw, [cx, cy, cz], [lobeR, lobeR * squash, lobeR], detail);
      continue;
    }

    // FOLIAGE: the same lobe, flattened into a leaf-like disc and tilted onto its own axis.
    // Both draws come from `rand` in a fixed order, so the plant stays deterministic and a
    // foliage plant differs from a mound plant only in orientation and proportion — which
    // is what makes the two panels a fair comparison of SILHOUETTE rather than of size.
    const yaw = rand() * Math.PI * 2;
    const tilt = 0.35 + rand() * 0.75;
    // The disc's own normal, tilted off vertical by `tilt` and swung to `yaw`.
    const up: [number, number, number] = [
      Math.sin(tilt) * Math.cos(yaw),
      Math.cos(tilt),
      Math.sin(tilt) * Math.sin(yaw),
    ];
    // Any vector not parallel to `up` gives the first tangent; Gram-Schmidt gives the rest.
    // `basisFromUp` is that construction, shared with the flower and tree generators.
    // Flattened along the disc's own normal: broad in its plane, thin across it.
    addLobe(
      raw,
      [cx, cy, cz],
      [lobeR * 1.25, lobeR * 0.34 * squash, lobeR * 1.05],
      detail,
      basisFromUp(up),
    );
  }

  return fitToFootprint(raw, spec.width, spec.height);
}

/** The mesh a SPRITE plant is, for the like-for-like comparison: a single flat quad wearing
 *  the plant's footprint. That is genuinely what a sprite is — a billboard — and stating it
 *  as geometry is what makes the two sides of the comparison commensurable rather than a
 *  picture beside a number. */
export function spriteQuad(width: number, height: number): PlantMesh {
  const raw: Raw = {
    pos: [-0.5, 0, 0, 0.5, 0, 0, 0.5, 1, 0, -0.5, 1, 0],
    nrm: [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1],
    idx: [0, 1, 2, 0, 2, 3],
  };
  return fitToFootprint(raw, width, height);
}
