import { test } from "node:test";
import assert from "node:assert/strict";

import {
  renderCodexGuidance,
  syncClaudeRegion,
  syncGeneratedGuidance,
} from "./claude-region.js";

const AGENT = "session-orchestrator";

/** A minimal CLAUDE.md skeleton with the agent markers, in the given EOL. */
function skeleton(regionBody: string, eol: "\n" | "\r\n"): string {
  return [
    "# storytree",
    "",
    "intro prose.",
    "",
    `<!-- AGENT:${AGENT} START (generated by pnpm build:guidance) -->`,
    "",
    regionBody,
    "",
    `<!-- AGENT:${AGENT} END -->`,
    "",
    "## Conventions",
    "trailing prose.",
    "",
  ].join(eol);
}

test("a CRLF file with an in-sync region is NOT reported stale (the Windows gate bug)", () => {
  const digest = "the digest body line one\nline two";
  // The on-disk file is fully CRLF; the digest we splice in is LF — the exact mismatch that made
  // `next === md` go spuriously STALE on a Windows checkout.
  const crlfMd = skeleton(digest.replace(/\n/g, "\r\n"), "\r\n");
  const res = syncClaudeRegion(crlfMd, AGENT, digest);
  assert.equal(res.ok, true);
  if (!res.ok) return;
  assert.equal(res.inSync, true, "an EOL-only difference must not register as stale");
});

test("the same content compares in-sync regardless of the file's EOL (LF vs CRLF)", () => {
  const digest = "alpha\nbeta\ngamma";
  const lf = syncClaudeRegion(skeleton(digest, "\n"), AGENT, digest);
  const crlf = syncClaudeRegion(skeleton(digest.replace(/\n/g, "\r\n"), "\r\n"), AGENT, digest);
  assert.equal(lf.ok && lf.inSync, true);
  assert.equal(crlf.ok && crlf.inSync, true);
});

test("a genuinely changed digest IS reported out of sync", () => {
  const md = skeleton("the OLD digest", "\r\n");
  const res = syncClaudeRegion(md, AGENT, "the NEW digest");
  assert.equal(res.ok, true);
  if (!res.ok) return;
  assert.equal(res.inSync, false);
  assert.match(res.next, /the NEW digest/);
  assert.doesNotMatch(res.next, /the OLD digest/);
});

test("a write preserves the source file's EOL — CRLF in, CRLF out (no mixed endings)", () => {
  const res = syncClaudeRegion(skeleton("old", "\r\n"), AGENT, "new digest");
  assert.equal(res.ok, true);
  if (!res.ok) return;
  assert.equal(res.inSync, false);
  // Every newline is a CRLF; no bare LF survives.
  assert.equal(/(^|[^\r])\n/.test(res.next), false, "no bare LF should remain in a CRLF write");
  assert.match(res.next, /new digest/);
});

test("a write preserves LF when the source is LF", () => {
  const res = syncClaudeRegion(skeleton("old", "\n"), AGENT, "new digest");
  assert.equal(res.ok, true);
  if (!res.ok) return;
  assert.equal(res.next.includes("\r\n"), false, "an LF source must not gain CRLF");
});

test("the START marker line is preserved verbatim (it carries the rest of the comment)", () => {
  const md = skeleton("old", "\n");
  const res = syncClaudeRegion(md, AGENT, "new");
  assert.equal(res.ok, true);
  if (!res.ok) return;
  assert.match(res.next, /<!-- AGENT:session-orchestrator START \(generated by pnpm build:guidance\) -->/);
});

test("missing markers fail closed with a clear error", () => {
  const res = syncClaudeRegion("# no markers here\n", AGENT, "digest");
  assert.equal(res.ok, false);
  if (res.ok) return;
  assert.match(res.error, /markers not found/);
});

test("Codex root guidance is a deterministic whole-file projection of the same digest", () => {
  const rendered = renderCodexGuidance(AGENT, "role\n\nworkflow");
  assert.match(rendered, /GENERATED from the Library `agent` tier/);
  assert.match(rendered, /canonical Library `session-orchestrator` agent/);
  assert.match(rendered, /role\n\nworkflow/);
  assert.equal(rendered.endsWith("\n"), true);
});

test("a missing or stale Codex guidance file is out of sync", () => {
  const expected = renderCodexGuidance(AGENT, "new digest");
  assert.equal(syncGeneratedGuidance(null, expected).inSync, false);
  assert.equal(syncGeneratedGuidance("old digest\n", expected).inSync, false);
});

test("Codex guidance comparison ignores EOL and preserves CRLF on rewrite", () => {
  const expected = renderCodexGuidance(AGENT, "line one\nline two");
  const crlf = expected.replace(/\n/g, "\r\n");
  assert.equal(syncGeneratedGuidance(crlf, expected).inSync, true);

  const rewritten = syncGeneratedGuidance("old\r\n", expected);
  assert.equal(rewritten.inSync, false);
  assert.equal(/(^|[^\r])\n/.test(rewritten.next), false);
});
