// The PURE core of the forest-world → public-website sync + drift gate (ADR-0093
// Decision 3 / Open call 3 — sync-into-submodule). The public `web/` submodule
// consumes the shared render core (`@storytree/forest-world`) as a SYNCED BUILD
// ARTIFACT, never as private source (the ADR-0066 Decision 3 / ADR-0056 boundary):
// `pnpm sync:web-engine` copies the core's browser-safe sources into the website's
// `src/lib/forest-world/` (each stamped @generated), and `pnpm check:web-engine`
// (the gate's drift guard) FAILS when the synced copy drifts from the core. So a
// studio look change in the core can't silently leave the public site stale — a
// submodule bump must carry a fresh sync. It is the render-core twin of
// check-web-grounding (which binds the site's CLAIMS to the ADRs); both run
// parent-side at submodule-bump granularity, reusing the ADR-0051/0052
// generated-view + drift pattern.
//
// This module is PURE (no node:fs, no process): the CLI shell (web-engine.ts) does
// the IO; tests drive these functions with in-memory fixtures.

/** Where the synced artifact lives, web-relative — the website imports from here. */
export const ENGINE_DIR = "src/lib/forest-world";

/**
 * Core source files that must be present for the sync to be meaningful — a guard
 * so a broken discovery (empty dir, wrong path) fails loudly instead of silently
 * syncing nothing. The website's render imports the scene-graph + the barrel.
 */
export const REQUIRED_ENGINE_FILES = ["scene.ts", "index.ts"] as const;

/** Drop a file from the sync set — test files (node:test, `node:` imports) and
 *  declaration maps never ship to the browser bundle. */
export function isEngineSource(file: string): boolean {
  return file.endsWith(".ts") && !file.endsWith(".test.ts") && !file.endsWith(".d.ts");
}

/** Normalise EOL so a CRLF checkout of the synced copy never reads as drift — the
 *  claude-region lesson (a naive compare went spuriously STALE on Windows). */
export function normalizeEol(s: string): string {
  return s.replace(/\r\n/g, "\n");
}

/** The @generated banner stamped atop each synced file: the generated-view marker
 *  (ADR-0051/0052) that tells a reader the edit surface is the core, not this copy. */
export function bannerFor(file: string): string {
  return (
    `// @generated by \`pnpm sync:web-engine\` — DO NOT EDIT THIS COPY.\n` +
    `// Synced from packages/forest-world/src/${file} in the storytree parent repo (the\n` +
    `// shared forest-world render core, ADR-0093). Edit the core there and re-sync; a\n` +
    `// stale copy fails the parent's \`check:web-engine\` gate.\n\n`
  );
}

/**
 * Rewrite the core's NodeNext `./x.js` relative imports to extensionless `./x` —
 * the website (Vite/Astro) resolves extensionless TS imports (its own modules use
 * that style), so this avoids depending on Vite's `.js`→`.ts` resolution quirk.
 * Only sibling/relative specifiers are touched; bare package specifiers (none in
 * the browser-safe core) are left alone.
 */
export function rewriteImports(source: string): string {
  return source.replace(/(from\s+["'])(\.\.?\/[^"']+?)\.js(["'])/g, "$1$2$3");
}

/** The full content of one synced file: the banner, then the core source with its
 *  relative imports made extensionless and EOL LF-normalised (platform-stable bytes). */
export function syncedContent(file: string, source: string): string {
  return bannerFor(file) + rewriteImports(normalizeEol(source));
}

export interface SyncedFile {
  /** The core source file name, e.g. "scene.ts". */
  readonly file: string;
  /** The web-relative destination path, e.g. "src/lib/forest-world/scene.ts". */
  readonly path: string;
  /** The exact content to write (banner + LF-normalised source). */
  readonly content: string;
}

/**
 * Compute the exact synced fileset from the core sources (file name → raw source).
 * Pure + deterministic: the same core always yields the same plan, so the sync
 * (which writes it) and the check (which compares against it) agree by construction.
 * Non-source files are filtered; the result is sorted for a stable order.
 */
export function computeSyncPlan(coreSources: ReadonlyMap<string, string>): SyncedFile[] {
  const plan: SyncedFile[] = [];
  for (const [file, source] of coreSources) {
    if (!isEngineSource(file)) continue;
    plan.push({ file, path: `${ENGINE_DIR}/${file}`, content: syncedContent(file, source) });
  }
  return plan.sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0));
}

export interface DriftProblem {
  readonly file: string;
  readonly reason: string;
}

/**
 * Compare the planned synced files against what is actually in the website's engine
 * dir. `readSynced(file)` returns the synced copy's content or null when absent;
 * `syncedFiles` is every file currently in the engine dir (to catch a STALE EXTRA —
 * a core file deleted upstream but its copy left behind). EOL-insensitive so a CRLF
 * checkout is not false drift.
 */
export function detectEngineDrift(
  plan: readonly SyncedFile[],
  readSynced: (file: string) => string | null,
  syncedFiles: readonly string[],
): DriftProblem[] {
  const problems: DriftProblem[] = [];
  const planned = new Set(plan.map((p) => p.file));

  for (const item of plan) {
    const actual = readSynced(item.file);
    if (actual === null) {
      problems.push({ file: item.file, reason: "missing from the synced copy — run `pnpm sync:web-engine`" });
      continue;
    }
    if (normalizeEol(actual) !== normalizeEol(item.content)) {
      problems.push({
        file: item.file,
        reason: "the synced copy is STALE — the core changed; re-run `pnpm sync:web-engine`",
      });
    }
  }

  for (const file of syncedFiles) {
    if (isEngineSource(file) && !planned.has(file)) {
      problems.push({
        file,
        reason: "no longer in the core — a stale leftover; re-run `pnpm sync:web-engine` to drop it",
      });
    }
  }

  return problems;
}
