import assert from "node:assert/strict";
import { test } from "node:test";

import {
  ENGINE_DIR,
  bannerFor,
  computeSyncPlan,
  detectEngineDrift,
  isEngineSource,
  normalizeEol,
  rewriteImports,
  syncedContent,
} from "./web-engine-sync.js";

// A tiny stand-in core: two source files + a test file + a non-ts file. Only the two
// sources are engine sources; the rest must be filtered out of the plan.
const CORE = new Map<string, string>([
  ["rng.ts", "export const hash = (s: string): number => s.length;\n"],
  ["scene.ts", "import { hash } from './rng.js';\nexport const buildScene = () => hash('x');\n"],
  ["scene.test.ts", "import { test } from 'node:test';\ntest('x', () => {});\n"],
  ["README.md", "# not synced\n"],
]);

test("isEngineSource keeps browser sources, drops tests / decls / non-ts", () => {
  assert.equal(isEngineSource("scene.ts"), true);
  assert.equal(isEngineSource("index.ts"), true);
  assert.equal(isEngineSource("scene.test.ts"), false);
  assert.equal(isEngineSource("scene.d.ts"), false);
  assert.equal(isEngineSource("README.md"), false);
});

test("computeSyncPlan syncs only engine sources, stamped + sorted under ENGINE_DIR", () => {
  const plan = computeSyncPlan(CORE);
  assert.deepEqual(
    plan.map((p) => p.file),
    ["rng.ts", "scene.ts"], // .test.ts + .md filtered, sorted
  );
  assert.deepEqual(
    plan.map((p) => p.path),
    [`${ENGINE_DIR}/rng.ts`, `${ENGINE_DIR}/scene.ts`],
  );
  // Each synced file is the @generated banner followed by the source, with relative
  // imports made extensionless for Vite (`./rng.js` → `./rng`).
  const scene = plan.find((p) => p.file === "scene.ts")!;
  assert.ok(scene.content.startsWith(bannerFor("scene.ts")));
  assert.ok(scene.content.includes("export const buildScene"));
  assert.match(scene.content, /@generated by `pnpm sync:web-engine`/);
  assert.match(scene.content, /DO NOT EDIT/);
  assert.match(scene.content, /from '\.\/rng'/); // .js stripped
  assert.ok(!scene.content.includes("'./rng.js'"));
});

test("rewriteImports strips .js from relative specifiers only", () => {
  assert.equal(rewriteImports("import { x } from './rng.js';"), "import { x } from './rng';");
  assert.equal(rewriteImports('export { y } from "../hex.js";'), 'export { y } from "../hex";');
  assert.equal(rewriteImports("import type { Pt } from './hex.js';"), "import type { Pt } from './hex';");
  // bare specifiers + non-.js relative paths are untouched
  assert.equal(rewriteImports("import a from 'node:fs';"), "import a from 'node:fs';");
  assert.equal(rewriteImports("import d from './data.json';"), "import d from './data.json';");
});

test("detectEngineDrift passes when the synced copy matches the plan", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content]));
  const problems = detectEngineDrift(
    plan,
    (f) => synced.get(f) ?? null,
    [...synced.keys()],
  );
  assert.deepEqual(problems, []);
});

test("detectEngineDrift flags a missing synced file", () => {
  const plan = computeSyncPlan(CORE);
  const problems = detectEngineDrift(plan, (f) => (f === "rng.ts" ? syncedContent("rng.ts", CORE.get("rng.ts")!) : null), ["rng.ts"]);
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "scene.ts");
  assert.match(problems[0]!.reason, /missing/);
});

test("detectEngineDrift flags a stale (content-drifted) synced file", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content]));
  synced.set("scene.ts", synced.get("scene.ts")! + "// a hand edit that drifted\n");
  const problems = detectEngineDrift(plan, (f) => synced.get(f) ?? null, [...synced.keys()]);
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "scene.ts");
  assert.match(problems[0]!.reason, /STALE/);
});

test("detectEngineDrift is EOL-insensitive — a CRLF checkout is not drift", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content.replace(/\n/g, "\r\n")]));
  const problems = detectEngineDrift(plan, (f) => synced.get(f) ?? null, [...synced.keys()]);
  assert.deepEqual(problems, []);
});

test("detectEngineDrift flags a stale leftover no longer in the core", () => {
  const plan = computeSyncPlan(CORE);
  const synced = new Map(plan.map((p) => [p.file, p.content]));
  synced.set("removed.ts", "// a core file that was deleted upstream\n");
  const problems = detectEngineDrift(plan, (f) => synced.get(f) ?? null, [...synced.keys()]);
  assert.equal(problems.length, 1);
  assert.equal(problems[0]!.file, "removed.ts");
  assert.match(problems[0]!.reason, /no longer in the core/);
});

test("normalizeEol collapses CRLF to LF", () => {
  assert.equal(normalizeEol("a\r\nb\r\n"), "a\nb\n");
});
