// detail-normal.test.ts — the drift guard on the embedded cliff normal map, and the shape check
// on the container.
//
// ⚠⚠ WHAT THIS FILE IS FOR. `src/detail-normal.ts` is a PROJECTION of
// `harness/assets/cliff-normal-128.png`, generated by `harness/build-detail-normal.mjs`, because
// the web sync carries only `.ts` and `.tsx` (`isEngineSource`, `packages/cli/src/web-engine-sync.ts`)
// and a `src/` module that fetched the file would 404 in the public engine copy. The pair is held
// together here byte for byte, in the direction that matters: the FILE is the source of truth and
// the module must agree with it — the same guard `kit-asset.test.ts` holds over the kit.
//
// ⚠ IT READS THE `.png` THROUGH `node:fs` AND THAT IS FINE. The scope fence is about IMPORTS — a
// `src/` module may not import `harness/` — and `.test.ts` files are dropped from the sync
// entirely, so nothing here reaches the browser bundle. The MODULE under test imports nothing.

import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  DETAIL_NORMAL_BYTES,
  DETAIL_NORMAL_PNG_BASE64,
  DETAIL_NORMAL_SHA256,
  DETAIL_NORMAL_SIZE,
  detailNormalBytes,
} from './detail-normal.js';

/** The committed derivative — the source of truth this module is a projection of. */
const PNG = readFileSync(
  fileURLToPath(new URL('../harness/assets/cliff-normal-128.png', import.meta.url)),
);

const sha256 = (b: Uint8Array): string => createHash('sha256').update(b).digest('hex');

/** The eight-byte PNG signature, as the spec lists it. */
const PNG_MAGIC = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

test('the embedded base64 IS the committed .png, re-derived from the file', () => {
  // ⚠ THE WHOLE POINT, and it is a comparison against the FILE rather than against a hash this
  // module also carries — a self-consistent module that had drifted from the asset would satisfy
  // any check that only asked whether its own constants agreed with each other.
  assert.equal(
    DETAIL_NORMAL_PNG_BASE64,
    PNG.toString('base64'),
    'the embedded base64 differs from harness/assets/cliff-normal-128.png — re-run harness/build-detail-normal.mjs',
  );
});

test('the decode returns the committed .png, byte for byte', () => {
  const decoded = detailNormalBytes();
  assert.equal(decoded.length, PNG.length, 'the embedded tile is a different length from the file');
  assert.ok(
    decoded.every((b, i) => b === PNG[i]),
    'the decoded bytes differ from harness/assets/cliff-normal-128.png',
  );
});

test('the declared byte count and hash are the committed file’s', () => {
  assert.equal(DETAIL_NORMAL_BYTES, PNG.length);
  assert.equal(DETAIL_NORMAL_SHA256, sha256(PNG));
});

test('what decodes really is a PNG — magic, IHDR, and a 128x128 RGB tile with no alpha', () => {
  // A hash comparison proves the bytes match the file; it does not prove the FILE is what an
  // image decoder will accept, nor that it is the shape the material assumes. The signature and
  // the IHDR chunk say so in independent places, read off the bytes rather than the filename.
  const bytes = detailNormalBytes();
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  for (const [i, expected] of PNG_MAGIC.entries()) {
    assert.equal(bytes[i], expected, `PNG signature byte ${i}`);
  }
  assert.equal(view.getUint32(8, false), 13, 'the first chunk is not a 13-byte IHDR');
  assert.equal(
    String.fromCharCode(bytes[12]!, bytes[13]!, bytes[14]!, bytes[15]!),
    'IHDR',
    'the first chunk is not IHDR',
  );
  assert.equal(view.getUint32(16, false), DETAIL_NORMAL_SIZE, 'IHDR width');
  assert.equal(view.getUint32(20, false), DETAIL_NORMAL_SIZE, 'IHDR height');
  assert.equal(DETAIL_NORMAL_SIZE, 128, 'the tile is not the 128-texel derivative');
  assert.equal(bytes[24], 8, 'IHDR bit depth — 8 bits per channel');
  // Colour type 2 = truecolour, no alpha. A normal map with an alpha channel would upload as RGBA
  // and cost a third more GPU memory for a channel the shader never reads; a palette or grey
  // image would not be a normal map at all.
  assert.equal(bytes[25], 2, 'IHDR colour type — RGB with no alpha');
});

test('⚠ the decode is not a UTF-8 encode — every byte above 0x7f survives it', () => {
  // `atob` returns a BINARY STRING, one byte per char; a `TextEncoder` over it would two-byte-
  // encode every char above 0x7f and corrupt the deflate stream. Asserting on the high bytes
  // specifically means the guard is about the mechanism, which a length check alone leaves open.
  const decoded = detailNormalBytes();
  const high = [...decoded].filter((b) => b > 0x7f).length;
  assert.ok(high > 1000, `only ${high} bytes above 0x7f — a deflated image must be full of them`);
  const highInFile = [...PNG].filter((b) => b > 0x7f).length;
  assert.equal(high, highInFile, 'the decode changed how many high bytes the tile has');
});

test('the decode returns a fresh array each call — a consumer may transfer or mutate it', () => {
  const a = detailNormalBytes();
  const b = detailNormalBytes();
  assert.notEqual(a, b, 'two calls returned the same Uint8Array');
  assert.deepEqual(a, b);
});

test('⚠ the drift check can actually fire — a one-byte difference is caught', () => {
  // NON-VACUITY. The comparisons above pass for a module that is correct AND for a comparison
  // that is broken; this proves it is the first. A mutated copy of the asset must fail the same
  // ways the real check would.
  const mutated = Uint8Array.from(PNG);
  mutated[mutated.length - 1] = (mutated[mutated.length - 1]! + 1) % 256;
  const decoded = detailNormalBytes();
  assert.ok(!decoded.every((b, i) => b === mutated[i]), 'a one-byte change was not detected');
  assert.notEqual(sha256(mutated), DETAIL_NORMAL_SHA256);
  assert.notEqual(Buffer.from(mutated).toString('base64'), DETAIL_NORMAL_PNG_BASE64);

  const shorter = PNG.subarray(0, PNG.length - 1);
  assert.notEqual(shorter.length, DETAIL_NORMAL_BYTES, 'a truncation was not detected');
});
