// kit-asset.test.ts — the drift guard on the embedded kit, and the shape check on the decode.
//
// ⚠⚠ WHAT THIS FILE IS FOR. `src/kit-asset.ts` is a PROJECTION of
// `harness/assets/dressing-kit.glb`, generated by `harness/build-kit-asset.mjs`, because the web
// sync carries only `.ts` and `.tsx` (`isEngineSource`, `packages/cli/src/web-engine-sync.ts`) and
// a `src/` module that fetched the file would 404 in the public engine copy. A projection with no
// drift check is how this package acquired three disagreeing status palettes and spent an
// increment putting them back together — so the pair is held together here, byte for byte, in the
// direction that matters: the FILE is the source of truth and the module must agree with it.
//
// ⚠ IT READS THE `.glb` THROUGH `node:fs` AND THAT IS FINE. The scope fence is about IMPORTS — a
// `src/` module may not import `harness/` — and `.test.ts` files are dropped from the sync
// entirely (`isEngineSource`), so nothing here reaches the browser bundle. The MODULE under test
// imports nothing at all.

import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { KIT_ASSET_BYTES, KIT_ASSET_SHA256, decodeKitAsset } from './kit-asset.js';
import { kitObjectNames } from './kit-vocabulary.js';

/** The committed asset — the source of truth this module is a projection of. */
const GLB = readFileSync(fileURLToPath(new URL('../harness/assets/dressing-kit.glb', import.meta.url)));

const sha256 = (b: Uint8Array): string => createHash('sha256').update(b).digest('hex');

/** The kit as it was committed until 2026-09-04 — the 128-texel export, kept beside the shipped
 *  file as the tree-detail page's control arm (`harness/shipped-detail-scene.ts`). */
const GLB_128 = readFileSync(fileURLToPath(new URL('../harness/assets/dressing-kit-128.glb', import.meta.url)));

/** Its hash, as the 2026-08-29 README recorded it — the file must be exactly that kit, or the
 *  control arm compares the native maps against something other than today's picture. */
const SHA256_128 = '6aaab1fad00cc7f49e65da7b59541911c449e814ada600ce936b86a6956c4af7';

test('⚠ the shipped kit is the NATIVE rung (ADR-0508 D1), and the 128 export kept for the comparison arm is the kit as it was', () => {
  assert.equal(sha256(GLB_128), SHA256_128, 'the comparison arm’s file is not the kit that shipped until this landing');
  assert.notEqual(KIT_ASSET_SHA256, SHA256_128, 'the embedded kit is still the 128-texel export');
  assert.equal(KIT_ASSET_SHA256, sha256(GLB), 'the declared hash is not the shipped file’s');
  assert.ok(
    KIT_ASSET_BYTES > GLB_128.length * 8,
    `native maps are an order of magnitude over the 128 rung, not ${KIT_ASSET_BYTES} against ${GLB_128.length}`,
  );
  assert.equal(decodeKitAsset().byteLength, KIT_ASSET_BYTES);
});

test('the embedded kit decodes to the committed .glb, byte for byte', () => {
  // ⚠ THE WHOLE POINT, and it is a comparison against the FILE rather than against a hash this
  // module also carries — a self-consistent module that had drifted from the asset would satisfy
  // any check that only asked whether its own constants agreed with each other.
  const decoded = new Uint8Array(decodeKitAsset());
  assert.equal(decoded.length, GLB.length, 'the embedded kit is a different length from the file');
  assert.ok(
    decoded.every((b, i) => b === GLB[i]),
    'the embedded kit differs from harness/assets/dressing-kit.glb — re-run harness/build-kit-asset.mjs',
  );
});

test('the declared byte count and hash are the committed file’s', () => {
  assert.equal(KIT_ASSET_BYTES, GLB.length);
  assert.equal(KIT_ASSET_SHA256, sha256(GLB));
});

test('⚠ the decode is not a UTF-8 encode — every byte above 0x7f survives it', () => {
  // ⚠ THE FAILURE THIS EXISTS FOR. `atob` returns a BINARY STRING, one byte per char; running it
  // through a `TextEncoder` instead would two-byte-encode every char above 0x7f and roughly
  // one-and-a-half the asset's length. It surfaces as a glTF parse error deep in a loader, naming
  // nothing. Asserting on the high bytes specifically means the guard is about the mechanism
  // rather than about the total, which a length check alone would leave open.
  const decoded = new Uint8Array(decodeKitAsset());
  const high = [...decoded].filter((b) => b > 0x7f).length;
  assert.ok(high > 1000, `only ${high} bytes above 0x7f — a binary asset must be full of them`);
  const highInFile = [...GLB].filter((b) => b > 0x7f).length;
  assert.equal(high, highInFile, 'the decode changed how many high bytes the asset has');
});

test('what decodes really is a glTF binary container — magic, version and declared length', () => {
  // A hash comparison proves the bytes match the file; it does not prove the FILE is what a loader
  // will accept. The 12-byte glb header says so in three independent places, and reading it here
  // means a truncated or half-written asset is named as one rather than reaching `parseAsync`.
  const view = new DataView(decodeKitAsset());
  assert.equal(
    String.fromCharCode(view.getUint8(0), view.getUint8(1), view.getUint8(2), view.getUint8(3)),
    'glTF',
    'the decoded bytes do not start with the glb magic',
  );
  assert.equal(view.getUint32(4, true), 2, 'glb container version');
  assert.equal(view.getUint32(8, true), KIT_ASSET_BYTES, 'the glb header disagrees with its own size');
});

test('the decode returns a fresh buffer each call — a consumer may transfer or mutate it', () => {
  // `GLTFLoader.parseAsync` is free to take ownership of what it is handed. Returning one shared
  // buffer would mean a second island's load got whatever the first left behind, which is the kind
  // of defect that only appears once something mounts two canvases.
  const a = decodeKitAsset();
  const b = decodeKitAsset();
  assert.notEqual(a, b, 'two calls returned the same ArrayBuffer');
  assert.deepEqual(new Uint8Array(a), new Uint8Array(b));
});

test('⚠ the drift check can actually fire — a one-byte difference is caught', () => {
  // NON-VACUITY. The comparison above passes for a module that is correct AND for a comparison
  // that is broken; this proves it is the first. A mutated copy of the asset must fail the same
  // three ways the real check would.
  const mutated = Uint8Array.from(GLB);
  mutated[mutated.length - 1] = (mutated[mutated.length - 1]! + 1) % 256;
  const decoded = new Uint8Array(decodeKitAsset());
  assert.ok(!decoded.every((b, i) => b === mutated[i]), 'a one-byte change was not detected');
  assert.notEqual(sha256(mutated), KIT_ASSET_SHA256);

  const shorter = GLB.subarray(0, GLB.length - 1);
  assert.notEqual(shorter.length, KIT_ASSET_BYTES, 'a truncation was not detected');
});

test('⚠ the asset is SELF-CONTAINED — no chunk of it lives at a URI a loader would have to fetch', () => {
  // ⚠⚠ THIS IS WHAT LICENSES `parseKit` PASSING AN EMPTY BASE PATH, and the annotation on that
  // line names this test. `GLTFLoader.parseAsync(bytes, path)` resolves every external `uri` in
  // the JSON against `path`; a `.glb` that referenced its buffer or an image externally would
  // therefore load correctly in the harness (served off vite beside the file) and 404 in the
  // public engine copy, which carries `.ts` only. A container with exactly two chunks — JSON and
  // BIN — and no `uri` anywhere has nothing to resolve, so the base path cannot matter.
  const bytes = new Uint8Array(decodeKitAsset());
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);

  const chunks: Array<{ type: number; start: number; length: number }> = [];
  let at = 12;
  while (at + 8 <= bytes.length) {
    const length = view.getUint32(at, true);
    const type = view.getUint32(at + 4, true);
    chunks.push({ type, start: at + 8, length });
    at += 8 + length + ((4 - (length % 4)) % 4);
  }
  assert.equal(chunks.length, 2, `the container holds ${chunks.length} chunks, not JSON + BIN`);
  assert.equal(chunks[0]!.type, 0x4e4f534a, 'the first chunk is not JSON');
  assert.equal(chunks[1]!.type, 0x004e4942, 'the second chunk is not BIN — the buffer is external');

  const json = Buffer.from(
    bytes.subarray(chunks[0]!.start, chunks[0]!.start + chunks[0]!.length),
  ).toString('utf8');
  const gltf = JSON.parse(json) as {
    buffers?: Array<{ uri?: string }>;
    images?: Array<{ uri?: string }>;
  };
  // NON-VACUITY: the asset really does carry both kinds of resource, so "none of them is external"
  // is a fact about this kit rather than about an empty list.
  assert.ok((gltf.buffers ?? []).length > 0, 'the glTF declares no buffer at all');
  assert.ok((gltf.images ?? []).length > 0, 'the glTF declares no image at all');
  for (const b of gltf.buffers ?? []) assert.equal(b.uri, undefined, 'a buffer lives at a URI');
  for (const i of gltf.images ?? []) assert.equal(i.uri, undefined, 'an image lives at a URI');
  assert.ok(!json.includes('"uri"'), 'the glTF JSON still names a uri somewhere');
});

/** The glTF JSON the container carries, parsed off the decoded bytes — the same chunk walk the
 *  self-contained test does, hoisted so two tests can ask the document different questions. */
function gltfDocument(): {
  nodes?: Array<{ name?: string }>;
  meshes?: Array<{ name?: string }>;
  materials?: Array<{ name?: string }>;
  images?: Array<{ name?: string }>;
} {
  const bytes = new Uint8Array(decodeKitAsset());
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const length = view.getUint32(12, true);
  const json = Buffer.from(bytes.subarray(20, 20 + length)).toString('utf8');
  return JSON.parse(json) as ReturnType<typeof gltfDocument>;
}

test('⚠⚠ THE ASSET CARRIES EXACTLY THE OBJECTS THE VOCABULARY NAMES — no more, and none missing', () => {
  // ⚠ THE DIRECTION OF EACH HALF IS DIFFERENT AND BOTH ARE NEEDED. A MISSING object is a role that
  // draws nothing — an island quietly short of its bushes, with no error anywhere. An EXTRA object
  // is dead weight the browser downloads and decodes forever, and it is the shape a re-export
  // acquires by accident: the KEEP list is a CSV argument typed by hand at a Blender command line.
  const doc = gltfDocument();
  const nodes = (doc.nodes ?? []).map((n) => n.name ?? '').filter((n) => n !== '');
  assert.ok(nodes.length > 0, 'the glTF declares no node at all');
  assert.deepEqual([...new Set(nodes)].sort(), [...kitObjectNames()].sort());
});

test('⚠⚠ IT IS THE NODE NAME THAT IS THE OBJECT NAME — the MESH names disagree, and that is the kit’s', () => {
  // ⚠⚠ A TRAP MEASURED ON THIS ASSET 2026-09-04, recorded because the two lists look
  // interchangeable and are not. Blender exports the OBJECT name onto the glTF node and the MESH
  // DATABLOCK name onto the mesh, and this kit's `Leafy_Plant_01` / `Leafy_Plant_02` objects carry
  // datablocks the pack's author called `Leafy_Bush_01` / `Leafy_Bush_02`. So a lookup written
  // against `meshes[].name` would fail to find the two objects the vocabulary DOES place, and
  // would appear to find two the export deliberately EXCLUDED — `Leafy_Bush_*` are separate
  // objects on a fourth material (`COVER_GAP_2026_09_03`), and the whole payload argument for this
  // landing is that no fourth material shipped. `kit-mesh.ts` resolves by node, which is correct;
  // this pins the fact so the next reader does not have to rediscover it from a wrong count.
  const doc = gltfDocument();
  const nodes = [...new Set((doc.nodes ?? []).map((n) => n.name ?? ''))].sort();
  const meshes = [...new Set((doc.meshes ?? []).map((m) => m.name ?? ''))].sort();
  assert.notDeepEqual(meshes, nodes, 'the two name lists agree now — this trap has gone and so may this test');
  assert.ok(meshes.includes('Leafy_Bush_01') && meshes.includes('Leafy_Bush_02'));
  assert.ok(!nodes.includes('Leafy_Bush_01'), 'a Leafy_Bush OBJECT reached the export — that is the fourth material');
  assert.ok(nodes.includes('Leafy_Plant_01') && nodes.includes('Leafy_Plant_02'));
  assert.equal(meshes.length, nodes.length, 'one mesh per object either way');
});

test('⚠⚠ THE GROUND-COVER SUBSET ADDED NO MATERIAL, and that is the whole payload argument', () => {
  // ⚠ THIS IS THE CLAIM THE 2026-09-04 LANDING RESTS ON, pinned at the asset rather than left in a
  // README. Since ADR-0508 D1 the kit ships its NATIVE 2048-texel maps, so a material is not a
  // rounding error: a FOURTH one costs three more 2048² textures with their mip chains, about
  // 67 MB of texture memory on top of the 201 MB the kit already holds. The six ground-cover
  // objects were chosen to sit on the three the kit already carried — which is why the subset
  // costs 3.9% over the wire and not one texel — and the kit's own `COVER_GAP_2026_09_03` records
  // what was left out for exactly this reason (the `Leafy_Bush_*` and the yellow flowers, both on
  // `Pine_Foliage_02`). A re-export that widened the KEEP list would pass every byte-for-byte
  // check in this file and blow the VRAM figure silently.
  const doc = gltfDocument();
  const materials = (doc.materials ?? []).map((m) => m.name ?? '').sort();
  assert.deepEqual(materials, ['Pine_Branches', 'Pine_Forest_Foliage', 'Pine_Trunks']);
  // And the textures they carry: three per material, which is what the 201 MB GPU figure counts.
  assert.equal((doc.images ?? []).length, 9, 'the kit carries a different number of texture images');
});
